### PR TITLE
Augment the Readme with extended help on using the RSpec mock data

### PR DESCRIPTION
**Pull request by woodpigeon**

### CODE REVIEW

**Comment by autotelik** [comment]
worth mentioning that in your tests you can only use the exact postcodes/urns mentioned in the address yaml file

**Comment by autotelik** [comment]
cos if you use anything else you get this 

  WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET http://addressfacade.cloudapp.net/address-service/v1/addresses/10010175140?client-id=example%20team1&key=client1 with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip, deflate', 'Host'=>'addressfacade.cloudapp.net', 'User-Agent'=>'rest-client/2.0.0.rc2 (linux-gnu x86_64) ruby/2.3.1p112'}
     
       You can stub this request with the following snippet:
     
       stub_request(:get, "http://addressfacade.cloudapp.net/address-service/v1/addresses/10010175140?client-id=example%20team1&key=client1").
         with(:headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip, deflate', 'Host'=>'addressfacade.cloudapp.net', 'User-Agent'=>'rest-client/2.0.0.rc2 (linux-gnu x86_64) ruby/2.3.1p112'}).
         to_return(:status => 200, :body => "", :headers => {})

**Comment by reggieb** [comment]
:ship: it

**Comment by woodpigeon** [comment]
@autotelik Have added some new tests to check for that error but cannot reproduce the behaviour you are seeing yet. Removing VCR from the engine that uses this gem might resolve the issue.

**Pull request merged**
